# Generated by Django 3.0.2 on 2020-01-25 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('jq', 'JQuery'), ('re', 'React'), ('an', 'Angular'), ('vu', 'Vue'), ('php', 'PHP'), ('lv', 'Laravel'), ('sy', 'Symfony'), ('no', 'Node.js'), ('ex', 'Express.js'), ('my', 'MySQL'), ('ps', 'PostgresQl'), ('md', 'MongoDB'), ('py', 'Python'), ('dj', 'Django'), ('fl', 'Flask'), ('ja', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('cs', 'C#'), ('oc', 'Objective-C'), ('sw', 'Swift'), ('go', 'Go'), ('rs', 'Rust'), ('rb', 'Ruby'), ('rr', 'Ruby On rails')], max_length=87)),
                ('deadline', models.DateField()),
                ('budget', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('taken', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('applicants', models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
